### ISSUE TITLE
Invalid package.json

### ISSUE THREAD

**Issue by ThatGuyJamal** [xhayper/slash-register#1]
Error using this package.

`slash-register/dist/index.js'. Please verify that the package.json has a valid "main" entry`

```
code: 'MODULE_NOT_FOUND',
path: '/home/thatguyjamal/Code/bots/backend/node_modules/slash-register/package.json',
requestPath: 'slash-register'
```

**Comment by xhayper** [comment]
The problem with this is because author was using his github of the library, which doesn't have compiled output, leading to this error.
